### ISSUE TITLE
IMF country code has missing values 

### ISSUE THREAD

**Issue by Yingjie4Science** [vincentarelbundock/countrycode#361] opened 2024-12-16 22:13 UTC
the sourcevar should allow to be character when origin = 'imf' 
see https://data.imf.org/api/document/download?key=61358699

**Comment by cjyetman** [comment] 2024-12-16 22:23
Can you describe in more detail what you're looking for? Normally the IMF country code would be used like this...
``` r
library(countrycode)

countrycode(
  sourcevar = c(132, 134, 174),
  origin = "imf",
  destination = "country.name"
)
#> [1] "France"  "Germany" "Greece"

countrycode(
  sourcevar = c("France", "Germany", "Greece"),
  origin = "country.name",
  destination = "imf"
)
#> [1] 132 134 174
```

**Comment by cjyetman** [comment] 2024-12-16 22:29
If you have a character vector that you believe is using precisely country names that IMF typically uses and you want to convert that to some other country code, like ISO3c, you'd probably want to use
``` r
library(countrycode)

countrycode(
  sourcevar = c("France", "Germany", "Greece"),
  origin = "country.name",
  destination = "iso3c"
)
#> [1] "FRA" "DEU" "GRC"
```
because `origin = "country.name"` tells `countrycode()` to use its fancy regex matching to match any known variations of country names (including anything IMF would use) to whatever country code is specified by `destination`.

**Comment by vincentarelbundock** [comment] 2024-12-16 23:13
closing because the `imf` code is clearly numeric. Users should either convert their codes to numeric if they are character before calling `countrycode`, or they should use `country.name` as `origin` to convert long form country names into codes.

Feel free to comment again if you feel we have misunderstood your suggestion. If you do so, please provide more detail. It is very difficult to understand your exact request with such a terse issue.

**Closed by vincentarelbundock** 2024-12-16 23:13 UTC

**Comment by cjyetman** [comment] 2024-12-17 00:20
For completeness sake (since @vincentarelbundock probably interpreted the request properly where I failed 🤦), if your variable containing IMF codes is a character vector even though the values represent the numeric IMF country codes, simply convert them to numeric before passing to `countrycode()`, e.g.

``` r
library(countrycode)

countrycode(
  sourcevar = as.numeric(c("132", "134", "174")),
  origin = "imf",
  destination = "country.name"
)
#> [1] "France"  "Germany" "Greece"
```

**Comment by Yingjie4Science** [comment] 2024-12-17 06:57
@vincentarelbundock @cjyetman Thanks both! Please see my updated post.

**Comment by cjyetman** [comment] 2024-12-17 11:43
### Monaco
Monaco does not appear in the PDF that you linked to, and so it appears that IMF does not have a code for Monaco. Where did you get `183` from?

### Kosovo
Kosovo has an IMF code 967 that does appear in our data. It does *not* have an IS03c code, therefore `NA` is correctly returned if IMF code 967 is converted to ISO3c.

``` r
library(countrycode)

countrycode(
  sourcevar = c("Kosovo"),
  origin = "country.name",
  destination = "imf"
)
#> [1] 967

countrycode(
  sourcevar = c("Kosovo"),
  origin = "country.name",
  destination = "iso3c"
)
#> Warning: Some values were not matched unambiguously: Kosovo
#> [1] NA

countrycode(
  sourcevar = c(976),
  origin = "imf",
  destination = "iso3c"
)
#> Warning: Some values were not matched unambiguously: 976
#> [1] NA
```

### Korea, Dem. People's Rep. of
Korea, Dem. People's Rep. of IMF code 954 is possibly a new IMF code that we do not currently have in our data here. I will have to track down a link to the official IMF country code specification to verify that.

### World
"World" is a region, not a country, therefore we do not support it. The IMF codes by design, as far as I understand, do not use codes that start or end with 0 for countries, so it is not necessary to support codes in the form "0xx" or "xx0".

**Comment by cjyetman** [comment] 2024-12-17 13:16
``` r
library(readr)
library(dplyr)

# from https://www.imf.org/en/Publications/WEO/weo-database/2024/October/download-entire-database

weo_url <- "https://www.imf.org/-/media/Files/Publications/WEO/WEO-Database/2024/October/WEOOct2024all.ashx"

download.file(weo_url, "weo.tsv")

weo <-
  readr::read_delim(
    file = "weo.tsv",
    delim = "\t",
    locale = readr::locale(encoding = "UTF-16LE"),
    show_col_types = FALSE
  )
#> New names:
#> • `` -> `...61`

weo_codes <-
  weo %>% 
  select(weo = `WEO Country Code`, iso3c = ISO, country.name = Country) %>% 
  distinct()

weo_codes %>% 
  filter(grepl("monaco|korea|kosovo", country.name, ignore.case = TRUE))
#> # A tibble: 2 × 3
#>     weo iso3c country.name
#>   <dbl> <chr> <chr>       
#> 1   542 KOR   Korea       
#> 2   967 UVK   Kosovo

weo_codes %>% 
  filter(weo %in% c(967, 954, 183))
#> # A tibble: 1 × 3
#>     weo iso3c country.name
#>   <dbl> <chr> <chr>       
#> 1   967 UVK   Kosovo
```

**Comment by NilsEnevoldsen** [comment] 2024-12-17 16:20
Current IMF codes in `countryside` are not fetched by a getter. I don't know exactly where they're from, but they might be from the WEO, like CJ posted.

"DOTS" codes appear to be 1:1 with "WEO" codes where both exist. But there are also DOTS codes for non-members, like Cuba, North Korea, East Germany, and the USSR. (https://www.elibrary.imf.org/downloadpdf/book/9781451948431/back-1.xml)

I don't know whether "DOTS" codes or "WEO" codes are a better choice to represent "IMF" codes.

Is that a proper summary?

**Comment by cjyetman** [comment] 2024-12-17 16:42
My impression is that IMF typically uses ISO country codes, except For WEO, which seems to have its own (pseudo) numeric code set.

**Comment by cjyetman** [comment] 2024-12-23 17:56
I sent a query to WEO asking if there's a publicly available, official record of their country codes, and they pointed me to the same file I used above (which unfortunately is the entire dataset, and inherently specific to a certain release as opposed to being universal across releases)

> Response
> You can select WEO Country Code, ISO Alpha-3 Code, Country name – when downloading the dataset here: https://www.imf.org/en/Publications/WEO/weo-database/2024/October/select-country-group
> Or after downloading the entire dataset here: https://www.imf.org/en/Publications/WEO/weo-database/2024/October/download-entire-database
>  
> Best,
> WEO Team

**Comment by vincentarelbundock** [comment] 2024-12-31 12:52
Thanks for going the extra mile @cjyetman !!

What's your current view on this? Is there anything we need to change?

**Comment by cjyetman** [comment] 2024-12-31 13:45
> What's your current view on this? Is there anything we need to change?

Don't thing there's anything critical here, but...

1. There's a WEO code for North Korea "in the wild" that we don't have in our data
2. Our `imf` should maybe be `weo`, because it appears those codes are only used in WEO and otherwise IMF uses iso
3. WEO apparently does not provide an official lookup table of their country codes that spans multiple years/releases of their data. Their "official" advice/response to me was to take the columns from the data itself 🤷, and it's clear that different releases include or don't include various countries, so there's no single complete source.

**Comment by vincentarelbundock** [comment] 2024-12-31 15:04
Yeah, that makes sense.

I don't think we want to rename `imf` to `weo`, for backward compatibility. But I do agree that people should use a different code. 

I've added a note to the docs:

24fe0d27c45733974ea5bb2ffc95062706ccc5c5

**Comment by vincentarelbundock** [comment] 2025-01-12 15:13
@cjyetman was just telling a friend about how cool it is that you and @NilsEnevoldsen still hang out here from time to time, willing to cold-email international organizations to get to the bottom of things.

Fun.
