### ISSUE TITLE
iso2n not recognized

### ISSUE THREAD

**Issue by Ajzach1** [vincentarelbundock/countrycode#216] opened 2020-03-05 16:48 UTC
I'm using countrycode 1.1.1 library for R and according to it's documentation, iso2n should be recognized both as origin and destination. Still, this happens to me:

    > countries_char <- countrycode(countries, origin = 'iso2n', destination 
    =  'iso2c')
    _Error in countrycode(countries, origin = "iso2n", destination = "iso2c"): 
    Origin code not supported by countrycode or present in the user-supplied 
     custom_dict._

'countries' is just a character vector. Is it a bug?

**Comment by vincentarelbundock** [comment] 2020-03-05 17:01
Thanks a lot for the report. 

The problem is that the `iso2n` code does not actually exist. Think about it: there are more than 100 countries, so you can't represent them all using just 2 numbers.

I have fixed the mistake in the documentation and pushed it to Github. It will be part of the next CRAN release (when we have enough changes to warrant going through that whole process).

Thanks again!

**Comment by vincentarelbundock** [comment] 2020-03-05 17:02
to complete, valid iso codes are: iso3c, iso3n, and iso2c.

**Closed by vincentarelbundock** 2020-03-05 17:01 UTC

**Comment by Ajzach1** [comment] 2020-03-05 17:16
Oh, I guess I need to add some zeroes to make my code iso3c then, thanks!

**Comment by vincentarelbundock** [comment] 2020-03-05 17:17
well, iso3c would a *character* code. iso3n is the *numeric* iso code. You can find country mappings: 

https://en.wikipedia.org/wiki/ISO_3166-1_numeric

**Comment by Ajzach1** [comment] 2020-03-05 17:35
True, I meant iso3n. Anyway, I've converted country codes to a 3-digit format and get such error:

In countrycode(countries, origin = "iso3n", destination = "iso3c") :
  Some values were not matched unambiguously: 012, 031, 032, 036, 051, 076

What could be the issue?

**Comment by vincentarelbundock** [comment] 2020-03-05 17:37
Are you trying to convert strings? `countries` should be a numeric vector if you want to convert from iso3n

**Comment by Ajzach1** [comment] 2020-03-05 17:46
That was the issue, I thought I have to pass a character string to countrycode(). Surprisingly for me when `countries` were 3-digit strings, only those not starting with zero were converted to iso3c. After making `countries` numbers, everything is ok. Thanks for help and much needed library!

**Comment by vincentarelbundock** [comment] 2020-03-05 17:47
Pleasure!
